title: BridgePoints
email: josiah@bridgepoints.net
description: >-
  Connecting Students to Opportunity — BridgePoints facilitates real-world, school-based internships led by CTE teachers.
baseurl: ""  # Keep empty if publishing to the root of bridgepoints.net
url: "https://markdavisson1345.github.io/bridgepoints-site/"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github_username: markdavisson1345
